#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

echo "Fetching and importing database"
curl https://www.in2code.de/extensions/downloads/powermail-ddev-site/$CURRENT_BRANCH/db.tar.gz -o .project/data/db.sql.gz
ddev import-db --file=.project/data/db.sql.gz

echo "Fetching and extracting fileadmin"
curl https://www.in2code.de/extensions/downloads/powermail-ddev-site/$CURRENT_BRANCH/fileadmin.tar.gz -o .project/data/fileadmin.tar.gz
tar xf .project/data/fileadmin.tar.gz -C public

echo "Update Languages (needed for behaviour tests)"
ddev typo3 language:update

ddev describe

echo "Thanks for supporting 'EXT:powermail"
