services:
  web:
    volumes:
      - "~/.composer/cache/:/home/.composer/cache/"
    environment:
      # Env vars for auto setup of TYPO3
      ## See: https://docs.typo3.org/p/helhum/typo3-console/6.3/en-us/CommandReference/InstallSetup.html?highlight=typo3_install_db_driver#install-setup
      - TYPO3_CONTEXT=Development
      - TYPO3_INSTALL_WEB_SERVER_CONFIG=none
      - TYPO3_INSTALL_DB_DRIVER=mysqli
      - TYPO3_INSTALL_DB_USER=db
      - TYPO3_INSTALL_DB_PASSWORD=db
      - TYPO3_INSTALL_DB_HOST=db
      - TYPO3_INSTALL_DB_PORT=3306
      - TYPO3_INSTALL_DB_UNIX_SOCKET=
      - TYPO3_INSTALL_DB_USE_EXISTING=1
      - TYPO3_INSTALL_DB_DBNAME=db
      - TYPO3_INSTALL_ADMIN_USER=admin
      - TYPO3_INSTALL_ADMIN_EMAIL=service@in2code.de
      - TYPO3_INSTALL_ADMIN_PASSWORD=Password1!
      - TYPO3_INSTALL_SITE_NAME=$DDEV_SITENAME (on DDEV)
      - TYPO3_INSTALL_SITE_SETUP_TYPE=no

      # test environment for testing framework
      - typo3DatabaseName=db_tests
      - typo3DatabaseHost=db
      - typo3DatabaseUsername=root
      - typo3DatabasePassword=root
